name: All Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["main", "master"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: github-metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: umbertocicciaa
          template: classic
          base: header, activity, community, repositories, metadata
          repositories_forks: yes

  intro:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics/intro.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: umbertocicciaa
          template: classic
          base: header, repositories
          plugin_introduction: yes
          repositories_forks: yes

  calendar_iso:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics/calendar-iso.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: umbertocicciaa
          template: classic
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

  languages:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics/languages.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: umbertocicciaa
          template: classic
          base: ""
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          repositories_forks: yes

  stargazers:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics/stargazers.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: umbertocicciaa
          template: classic
          base: ""
          plugin_stargazers: yes
          plugin_stargazers_charts_type: classic
          repositories_forks: yes

  habits:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics/habits.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: umbertocicciaa
          template: classic
          base: ""
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_habits_charts_type: classic
          repositories_forks: yes

  calendar:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics/calendar.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: umbertocicciaa
          template: classic
          base: ""
          plugin_calendar: yes
          plugin_calendar_limit: 1
          repositories_forks: yes

  activity:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics/activity.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: umbertocicciaa
          template: classic
          base: ""
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_load: 300
          plugin_activity_days: 14
          plugin_activity_visibility: all
          plugin_activity_timestamps: yes
          plugin_activity_filter: all
          repositories_forks: yes

  anilist:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics/anilist.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: umbertocicciaa
          template: classic
          base: ""
          plugin_anilist: yes
          plugin_anilist_medias: anime, manga
          plugin_anilist_sections: favorites, watching, reading
          plugin_anilist_limit: 2
          plugin_anilist_limit_characters: 22
          plugin_anilist_shuffle: yes
          plugin_anilist_user: JigenxOhtsusuki

  terminal:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics/terminal.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: umbertocicciaa
          template: terminal
          base: header, activity, community, repositories, metadata
          repositories_forks: yes